name: SLK Style
favicon: null
layout_spectrum: 0.7591
typography_spectrum: 1
title: 'Suzanne Kopulos: Stylist & Fashion Expert'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7e7881'
    - '#ffffff'
    - '#fcd4ca'
    - '#ada9af'
    - '#9f9094'
  brandStrength: 0.9598714620806277
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
